CREATE TABLE `events` (
  `event_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) DEFAULT NULL,
  `organizer` varchar(20) DEFAULT NULL,
  `description` text,
  `add_info` varchar(45) DEFAULT NULL,
  `date` datetime DEFAULT CURRENT_TIMESTAMP,
  `create_date` datetime DEFAULT CURRENT_TIMESTAMP,
  `venue` varchar(75),
  `latitude` double,
  `longitude` double,
  `type` varchar(25) DEFAULT NULL,
  `image` varchar(60000) DEFAULT NULL,
  `event_website` varchar(45) DEFAULT NULL,
  `twitter` varchar(225) DEFAULT NULL,
  `facebook` varchar(225) DEFAULT NULL,
  `status` varchar(10) DEFAULT 'pending',
  `event_amt` int(11) NOT NULL DEFAULT '20',
  `view` int(10) NOT NULL DEFAULT '0',
  `unique_str_id` varchar(50) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `event_id_UNIQUE` (`event_id`),
  KEY `username_idx` (`organizer`),
  CONSTRAINT `username` FOREIGN KEY (`organizer`) REFERENCES `organizer` (`username`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=98 DEFAULT CHARSET=latin1